package rms.rakutenpay.order.api.client

import org.joda.time.{DateTime, LocalDate}

case class OrderModel(
                       orderNumber: String,
                       orderProgress: Int,
                       subStatusId: Option[Int],
                       subStatusName: Option[String],
                       orderDatetime: DateTime,
                       shopOrderCfmDatetime: Option[DateTime],
                       orderFixDatetime: Option[DateTime],
                       shippingInstDatetime: Option[DateTime],
                       shippingCmplRptDatetime: Option[DateTime],
                       cancelDueDate: Option[LocalDate],
                       deliveryDate: Option[LocalDate],
                       shippingTerm: Option[Byte],
                       remarks: Option[String],
                       giftCheckFlag: Byte,
                       severalSenderFlag: Byte,
                       equalSenderFlag: Byte,
                       isolatedIslandFlag: Byte,
                       rakutenMemberFlag: Byte,
                       carrierCode: Byte,
                       emailCarrierCode: Byte,
                       orderType: Byte,
                       reserveNumber: Option[String],
                       reserveDeliveryCount: Option[Int],
                       cautionDisplayType: Byte,
                       rakutenConfirmFlag: Byte,
                       goodsPrice: Long,
                       goodsTax: Int,
                       postagePrice: Int,
                       deliveryPrice: Int,
                       totalPrice: Long,
                       requestPrice: Long,
                       couponAllTotalPrice: Long,
                       couponShopPrice: Long,
                       couponOtherPrice: Long,
                       asurakuFlag: Byte,
                       drugFlag: Byte,
                       dealFlag: Byte,
                       membershipType: Byte,
                       memo: Option[String],
                       operator: Option[String],
                       mailPlugSentence: Option[String],
                       modifyFlag: Byte,
                       isTaxRecalc: Byte,
                       OrdererModel: OrdererModel,
                       SettlementModel: Option[SettlementModel],
                       DeliveryModel: DeliveryModel,
                       PointModel: Option[PointModel],
                       WrappingModel1: Option[WrappingModel],
                       WrappingModel2: Option[WrappingModel],
                       PackageModelList: List[PackageModel],
                       CouponModelList: List[CouponModel],
                       ChangeReasonModel: List[ChangeReasonModel]
                     )
